version: 2
updates:
  - package-ecosystem: "bundler" # Para proyectos Jekyll en GitHub Pages
    directory: "/"               # Ubicaci√≥n del archivo Gemfile
    schedule:
      interval: "weekly"         # Revisa actualizaciones cada semana
