app = "faes-anubis"

[build]
image = "ghcr.io/techarohq/anubis:latest"

[http_service]
internal_port = 9090
force_https = true
min_machines_running = 1

[vm]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
